## Numpy Practice

In [4]:
import numpy as np
x=np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
L=[1,2,3,4]
print(L)
print(type(L))

[1, 2, 3, 4]
<class 'list'>


In [3]:
 %timeit [j**4 for j in range(1,9)]

997 ns ± 5.55 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


 ##### arange is used to create array from 1 to 8

In [6]:
%timeit np.arange(1,9)**4

2.42 µs ± 63.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [7]:
 a=[j**4 for j in range(1,9)]
print(a)

[1, 16, 81, 256, 625, 1296, 2401, 4096]


In [8]:
a=np.arange(1,9)
print(a)

[1 2 3 4 5 6 7 8]


In [9]:
a=np.arange(1,9)**4
print(a)

[   1   16   81  256  625 1296 2401 4096]


###### NumPy Arrays Creation

In [13]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [16]:
L=[1,2,3,4]
Y=np.array(L)
Y

array([1, 2, 3, 4])

In [22]:
L=[1,2,3,4]
L

[1, 2, 3, 4]

In [23]:
l=[]
for i in range(1,5):
    int_1 = input("Enter :")
    l.append(int_1)
l

Enter :1
Enter :2
Enter :3
Enter :4


['1', '2', '3', '4']

In [25]:
l=[]
for i in range(1,5):
    int_1 = int(input("Enter :"))
    l.append(int_1)
print(np.array(l))

Enter :1
Enter :2
Enter :3
Enter :5
[1 2 3 5]


##### Types of arrys
##### 1D  [1 2 3 4] 
##### 2D [[1 2 3 4]]
##### 3D [[[1 2 3 4]]]
##### Higher Dimensional arrays
##### ndim function can be used to identify array dimensions

In [27]:
l=[]
for i in range(1,5):
    int_1 = int(input("Enter :"))
    l.append(int_1)
print(np.array(l))
print("Dimension",np.array(l).ndim)

Enter :1
Enter :2
Enter :3
Enter :4
[1 2 3 4]
Dimension 1


In [28]:
ar2 = np.array([[1,2,3,4]])
print(ar2.ndim)

2


In [29]:
ar2 = np.array([[1,2,3,4],[1,2,3,4]])
print(ar2)

[[1 2 3 4]
 [1 2 3 4]]


In [30]:
ar2 = np.array([[1,2,3,4],[1,2,3]]) #length of all arrays should be same otherwise you will encounter error
print(ar2) 

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [31]:
ar3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [34]:
#multidimensional
#for 10 dimensional instead of 10 [] we have a shortcut using ndmin
arn = np.array([1,2,3,4],ndmin=10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


#### Zeros

In [5]:
import numpy as np
ar_zero = np.zeros(4) #one dimensional array is formed
ar_zero_md = np.zeros((3,4)) #3 rows and 4 columns
print(ar_zero)
print()
print(ar_zero_md)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### Ones

In [7]:
import numpy as np
ar_one = np.ones(4) #one dimensional array is formed
ar_one_md = np.ones((3,4)) #3 rows and 4 columns
print(ar_one)
print()
print(ar_one_md)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### Empty Array

In [8]:
ar_em = np.empty(4)
print(ar_em) #empty array is created


[1. 1. 1. 1.]


#### Range

In [9]:
ar_rn = np.arange(1,8)
print(ar_rn)

[1 2 3 4 5 6 7]


#### Making an Identity matrix or Diagnol as 1

In [10]:
ar_dia = np.eye(3)
print(ar_dia) #creates a 3x3 array

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
ar_dia = np.eye(3,5)
print(ar_dia) #creates a 3x5 array

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


#### array with spaced linearly in a specifed interval

In [12]:
#all elements will be present with a specific space
ar_lin = np.linspace(1,10,num=5) #1 to 10 with num of element as 5
print(ar_lin)

[ 1.    3.25  5.5   7.75 10.  ]


In [13]:
#all elements will be present with a specific space
ar_lin = np.linspace(0,10,num=5) #0 to 10 with num of element as 5
print(ar_lin)

[ 0.   2.5  5.   7.5 10. ]


In [18]:
ar_lin = np.linspace(2,10,num=5) #0 to 10 with num of element as 5
print(ar_lin)

[ 2.  4.  6.  8. 10.]


#### Random

In [20]:
#Rand() Function ranges between 0 to 1
import numpy as np
var = np.random.rand(4)
print(var)

[0.76175254 0.47572005 0.30865402 0.99261702]


In [26]:
#Rand() Function for multidimensional
import numpy as np
var = np.random.rand(2,4) #2 dimensional with 4 elements each
print(var)

[[0.51389089 0.78579476 0.6695838  0.27365002]
 [0.52530057 0.01342296 0.27582606 0.09000788]]


In [22]:
#Randn() Function gives positive and negative nums close to 0
import numpy as np
var = np.random.randn(4)
print(var)

[-0.63420016 -0.75279938 -0.61763292 -0.92639401]


In [27]:
#Randn() Function multidimensional
import numpy as np
var = np.random.randn(2,4)
print(var)

[[ 1.11122409  0.4464054  -2.30815505  0.72021626]
 [ 0.68402292 -1.44523111 -0.14974352  0.12111095]]


In [29]:
#Randf() Function #[0.0,1.0)
import numpy as np
var = np.random.ranf(4)
print(var)

[0.5885876  0.21389612 0.86093058 0.20659896]


In [32]:
#Randint() Function
import numpy as np
var = np.random.randint(1,8,4) #from to length
print(var)

[4 6 2 7]


#### DATA TYPES NUMPY ARRAY

In [33]:
#How to find what datatype is used in a particular numpy array
import numpy as np
var = np.array([1,2,3,4])
print("Data type : ",var.dtype)

Data type :  int32


In [35]:
var = np.array([1.2,5.62])
print("Data type : ",var.dtype)

Data type :  float64


In [37]:
var = np.array(["a","b","c"])
print("Data type : ",var.dtype)

Data type :  <U1


In [39]:
var = np.array([1,2,3,4,"a"]) #mix of data types
print("Data type : ",var.dtype)

Data type :  <U11


In [42]:
#DATA TYPE CONVERSION
x=np.array([1,2,3,4])
print("Data Type : ",x.dtype)
y=np.array([1,2,3,4],dtype=np.int8)
print("Data Type : ",y.dtype)

Data Type :  int32
Data Type :  int8


In [45]:
#SHORTCUT
#CONVERTING IT DIRECTLY TO FLOAT

y=np.array([1,2,3,4],dtype="f") #SHORTCUT f for float
print("Data Type : ",y.dtype)
print(y)

Data Type :  float32
[1. 2. 3. 4.]


In [47]:
#Conversion using functions
x2=np.array([1,2,3,4])

new = np.float32(x2)

print("Data Type : ",x2.dtype)
print("Data Type : ",new.dtype)

print(x2)
print(new)

Data Type :  int32
Data Type :  float32
[1 2 3 4]
[1. 2. 3. 4.]


In [48]:
#change type using astype
x3=np.array([1,2,3,4])

new_1 = x3.astype(float)
print(x3)
print(new_1)

[1 2 3 4]
[1. 2. 3. 4.]


### SHAPE AND RESHAPING IN NUMPY 

### Shape

In [2]:
import numpy as np
var=np.array([[1,2],[1,2]])

print(var)
print()
print(var.shape)

[[1 2]
 [1 2]]

(2, 2)


In [3]:
import numpy as np
var=np.array([[1,2,3,4],[1,3,4,2]])

print(var)
print()
print(var.shape)

[[1 2 3 4]
 [1 3 4 2]]

(2, 4)


In [5]:
var1 = np.array([1,2,3,4],ndmin=4)
print(var1)

[[[[1 2 3 4]]]]


In [6]:
var1 = np.array([1,2,3,4],ndmin=4)
print(var1)
print(var1.shape)

[[[[1 2 3 4]]]]
(1, 1, 1, 4)


### Reshape

In [10]:
#converting dimensions
var2 = np.array([1,2,3,4,5,6])
print(var2)
print()

x=var2.reshape(3,2) #num of rows,num of cols & its 2D Array

print(x)
print()
print(x.ndim)

[1 2 3 4 5 6]

[[1 2]
 [3 4]
 [5 6]]

2


In [12]:
#converting dimensions to 3 dimensions
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print()

x=var3.reshape(2,3,2) #num of rows, #num of rows inside that, #num of columns 

print(x)
print()
print(x.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

3


In [17]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print()

x=var3.reshape(2,3,2) #num of rows, #num of rows inside that, #num of columns 

print(x)
print()
print(x.ndim)
print()

y=x.reshape(-1) #it gets converted to one dimension
print(y)
print()
print(y.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

3

[ 1  2  3  4  5  6  7  8  9 10 11 12]

1


In [18]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print()

x=var3.reshape(2,3,2) #num of rows, #num of rows inside that, #num of columns 

print(x)
print()
print(x.ndim)
print()

y=x.reshape(-1,2) #it gets converted to one dimension
print(y)
print()
print(y.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

3

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

2


### ARITHMETIC OPERATION

In [20]:
import numpy as np

var = np.array([1,2,3,4])

varadd = var + 3  #all number added by 3
print(varadd)

[4 5 6 7]


In [28]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = var1 + var2
print(varadd)

[2 4 6 8]


In [29]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = np.add(var1,var2)
print(varadd)

[2 4 6 8]


In [22]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = var1 - var2
print(varadd)

[0 0 0 0]


In [24]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = var1 * var2
print(varadd)

[ 1  4  9 16]


In [25]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = var1 / var2
print(varadd)

[1. 1. 1. 1.]


In [27]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = var1 % 3
print(varadd)

[1 2 0 1]


In [34]:
varr = np.array([1,2,3,4])

varreci = np.reciprocal(varr)
print(varreci)

[1 0 0 0]


### 2D Array

In [31]:
var21 = np.array([[1,2,3,4],[1,2,5,4]])
var22 = np.array([[1,2,3,4],[0,2,6,4]]) 

varadd = var21 +var22
print(varadd)

[[ 2  4  6  8]
 [ 1  4 11  8]]


In [36]:
import numpy as np
var = np.array([1,2,3,4,5,3,2])

print("min : ",np.min(var),np.argmin(var)) #argmin provides position
print("min : ",np.max(var),np.argmax(var))



min :  1 0
min :  5 4


In [39]:
var1 = np.array([[2,1,3],[9,5,6]])
#Concept of axis
#axis 0 is towards column
#axis 1 is towards row
print(np.min(var1,axis=1)) #provides you column which has min values
print(np.min(var1,axis=0)) #provides you column which has min values

#But how we came to the conclusion
#it checks min of each column and then checks which column has the least
#this is the concept followed here

[1 5]
[2 1 3]


In [43]:
import numpy as np
var = np.array([1,2,3,4])

print("min : ",np.min(var),np.argmin(var)) #argmin provides position
print("min : ",np.max(var),np.argmax(var))
print("sqrt : ",np.sqrt(var))
print("sin : ",np.sin(var))
print("cos : ",np.cos(var))

min :  1 0
min :  4 3
sqrt :  [1.         1.41421356 1.73205081 2.        ]
sin :  [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
cos :  [ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [45]:
#Concept of cum sum
#A=[1,2,3]
#Output : [1,(1+2),(1+2+3)]

import numpy as np
var = np.array([1,2,3])

varcs = np.cumsum(var)
print(varcs)

[1 3 6]


### Broadcasting NumPy Arrays

In [1]:
import numpy as np

var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3])
print(var1+var2) #operands could not be broadcast together with shapes (4,) (3,) error occurs

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [10]:
import numpy as np

var1 = np.array([1,2,3])
print(var1)
print(var1.shape) #(3,) means 1x3
print()


var2 = np.array([[1],[2],[3]])
print(var2)
print(var2.shape) #(3,1) means x1
print()

#final array which will be formed is max of 1,3 and max of 1,3 so 3,3

print(var1+var2) #Two dimensions are compatible if they are equal or one of them is 1

[1 2 3]
(3,)

[[1]
 [2]
 [3]]
(3, 1)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [8]:
# In numpy, when you perform operations like addition on arrays, the arrays are subject to a concept called broadcasting. Broadcasting allows arrays of different shapes to be combined in element-wise operations like addition, subtraction, multiplication, etc., under certain conditions.

# In your example, you have two arrays: var1 and var2. Let's break down the shapes of these arrays and how broadcasting works in this case:

# var1 has a shape of (3,), which can also be represented as a 1-dimensional array with 3 elements.
# var2 has a shape of (3, 1), which can be thought of as a 3x1 matrix (3 rows and 1 column).
# When you perform the operation var1 + var2, numpy uses broadcasting to determine if the shapes of the arrays can be aligned for element-wise addition. The broadcasting rules are as follows:

# If the arrays have a different number of dimensions, left-pad the smaller shape with ones to match the number of dimensions of the larger shape.
# Compare the shapes element-wise, starting from the trailing dimensions. Two dimensions are compatible if they are equal or one of them is 1.
# If the dimensions are not compatible, a "ValueError: operands could not be broadcast together" is raised. Otherwise, the arrays can be broadcasted.
# In your case, the shapes are (3,) and (3, 1). Since the trailing dimensions are compatible (either equal or one of them is 1), numpy will automatically broadcast the arrays for element-wise addition.

# Here's how the broadcasting works for your example:

# The shape of var1 is broadcasted to (3, 3), replicating the original array along a new dimension. This effectively creates a 3x3 matrix with the values of var1 repeated along each row.
# The shape of var2 is broadcasted to (3, 3), replicating the original array along a new dimension. This effectively creates a 3x3 matrix with the values of var2 repeated along each column.
# Now, the addition is performed element-wise between the broadcasted arrays, resulting in a 3x3 matrix where each element is the sum of the corresponding elements from var1 and var2.

# In summary, the addition operation can be performed when the dimensions are compatible according to the broadcasting rules. In this case, broadcasting allows the 1x3 array and the 3x1 array to be added element-wise to produce a 3x3 result

In [2]:
import numpy as np
x=np.array([[1],[2]])
print(x.shape)

y=np.array([[1,2,3],[1,2,3]])
print(y.shape)

#2x1 and 2x3 moving from right to left we have 1 in 2x1 so work is done
print()
print(x+y)
#we will be getting output of 2x3 matrix

(2, 1)
(2, 3)

[[2 3 4]
 [3 4 5]]


### Indexing

In [4]:
import numpy as np
var=np.array([9,8,7,6])
            # 0 1 2 3

print(var[1]," ",var[-1])

8   6


In [15]:
var1 = np.array([[9,8,7],[4,5,6]])
print(var1)
print()
print(var1[0][1]) #first at 0th index we have [9 8 7] and then at index 1 we have 8
print(var1[0,1]) 

[[9 8 7]
 [4 5 6]]

8
8


In [14]:
var2 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(var2.ndim)
print()
print(var2)
print(var2[1,1,0])

3

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
7


### Slicing

In [22]:
#from array we try to get some particular data set
#slicing in 1D
#start:stop:step
var = np.array([1,2,3,4,5,6,7])
print(var)
a=var[2:5]
b=var[1:5:2]
c=var[2:] #2 to end
d=var[:] #all
e=var[:5] #start to 5
print(a)
print(b)
print(c)
print(d)
print(e)

[1 2 3 4 5 6 7]
[3 4 5]
[2 4]
[3 4 5 6 7]
[1 2 3 4 5 6 7]
[1 2 3 4 5]


In [35]:
#Slicing in 2D Array
var1 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(var1[0,1:])
print()
print(var1[1,1:])
print()
print(var1[1:])
print()
print(var1[2:])
print()
print(var1[2,0:])

[2 3 4 5]

[ 7  8  9 10]

[[ 6  7  8  9 10]
 [11 12 13 14 15]]

[[11 12 13 14 15]]

[11 12 13 14 15]


### Iteration

In [36]:
#Iterating 1D
import numpy as np

var =np.array([1,2,3,5,7])
for i in var:
    print(i)

1
2
3
5
7


In [38]:
#Iterating 2D
import numpy as np

var =np.array([[1,2,3,5,7],[1,2,3,5,7]])
for i in var:
    print(i)
print()

for i in var:
    for j in i:
        print(j)
        
#for 3D we will have 3 for loops

[1 2 3 5 7]
[1 2 3 5 7]

1
2
3
5
7
1
2
3
5
7


#### nditer() Function

In [47]:
#Iterating 2D
import numpy as np

var4 =np.array([[1,2,3,5,7],[1,2,3,5,7]])

for i in np.nditer(var4):
    print(i)
print()

#Parameters in nditer
#we can even change its data type
for i in np.nditer(var4,flags=['buffered'],op_dtypes=["S"]): #buffer creates extra space where iterated data can be stored
    print(i)
print()

#To print index number along with iteration
#ndenumerate() function can be used
for i in np.ndenumerate(var4):
    print(i)
print()

1
2
3
5
7
1
2
3
5
7

b'1'
b'2'
b'3'
b'5'
b'7'
b'1'
b'2'
b'3'
b'5'
b'7'

((0, 0), 1)
((0, 1), 2)
((0, 2), 3)
((0, 3), 5)
((0, 4), 7)
((1, 0), 1)
((1, 1), 2)
((1, 2), 3)
((1, 3), 5)
((1, 4), 7)



### Copy vs View

In [57]:
#Copy and view are basically used to copy
#There is a small difference between them thoo

import numpy as np

var=np.array([1,2,3,4])
co=var.copy()
print("Var : ",var)
print("Copy: ",co)
print()

#Concept of View
var=np.array([1,2,3,4])
view=var.view()
print("Var : ",var)
print("View: ",view)
print()

print("making changes in var[1]=14")
var[1]=14
print()
print("Var : ",var)
print("View: ",view)
print()
print("Var : ",var)
print("Copy: ",co)


Var :  [1 2 3 4]
Copy:  [1 2 3 4]

Var :  [1 2 3 4]
View:  [1 2 3 4]

making changes in var[1]=14

Var :  [ 1 14  3  4]
View:  [ 1 14  3  4]

Var :  [ 1 14  3  4]
Copy:  [1 2 3 4]


### Join Array

In [5]:
import numpy as np

var = np.array([1,2,3,4])
var1 = np.array([9,8,7,6])

ar = np.concatenate((var,var1))

print(ar)

[1 2 3 4 9 8 7 6]


In [10]:
#2D Array
vr = np.array([[1,2],[3,4]])
vr1 = np.array([[9,8],[7,6]])
print(vr)
print()
print(vr1)
print()
ar = np.concatenate((vr,vr1)) #by default it is concatenated along axis 0
print(ar)
print()
ar1 = np.concatenate((vr,vr1),axis=1) #concatenating along a
print(ar1)



[[1 2]
 [3 4]]

[[9 8]
 [7 6]]

[[1 2]
 [3 4]
 [9 8]
 [7 6]]

[[1 2 9 8]
 [3 4 7 6]]


##### Using Stack Function

In [21]:
import numpy as np

var_1 = np.array([1,2,3,4])
var_2 = np.array([9,8,7,6])

#stack function merges array and it works on the basis of axis
a_new = np.stack((var_1,var_2),axis=1)
a_new1 = np.stack((var_1,var_2),axis=0)
a_new2 = np.stack((var_1,var_2))
a_new3 = np.concatenate((var_1,var_2))
# a_new4 = np.concatenate((var_1,var_2),axis=1)

print("stack with axis = 1 \n",a_new,"\n\n")
print("stack with axis = 0 \n",a_new1,"\n\n")
print("stack without axis  \n",a_new2,"\n\n")
print("concatenate without axis \n",a_new3,"\n\n")
# print("concatenate with axis=1 \n",a_new4,"\n\n")
#AxisError: axis 1 is out of bounds for array of dimension 1

#we have 3 more stack function using which we can avoid axis
a_new5 = np.hstack((var_1,var_2)) #Row wise
a_new6 = np.vstack((var_1,var_2)) #Column wise
a_new7 = np.dstack((var_1,var_2)) #Height wise

print("hstack - row wise \n",a_new5,"\n\n")
print("vstack - column wise \n",a_new6,"\n\n")
print("hstack - height wise \n",a_new7,"\n\n")

stack with axis = 1 
 [[1 9]
 [2 8]
 [3 7]
 [4 6]] 


stack with axis = 0 
 [[1 2 3 4]
 [9 8 7 6]] 


stack without axis  
 [[1 2 3 4]
 [9 8 7 6]] 


concatenate without axis 
 [1 2 3 4 9 8 7 6] 


hstack - row wise 
 [1 2 3 4 9 8 7 6] 


vstack - column wise 
 [[1 2 3 4]
 [9 8 7 6]] 


hstack - height wise 
 [[[1 9]
  [2 8]
  [3 7]
  [4 6]]] 




### Split Array

In [24]:
import numpy as np

var = np.array([1,2,3,4,5,6])
print(var)

ar=np.array_split(var,3)

print()
print(ar)
print(ar[0])

[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]


In [29]:
#2D Array split into multiple 2D
import numpy as np

var1 = np.array([[1,2],[3,4],[5,6]])
print(var)

ar1=np.array_split(var1,3)
ar2=np.array_split(var1,3,axis=1)

print()
print(ar1)
print(ar1[0])
print()
print(ar2)
print(ar2[0])

[1 2 3 4 5 6]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
[[1 2]]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int32)]
[[1]
 [3]
 [5]]


### Searchinggg

In [33]:
#Search Array : Search an array for a certain value, and return the indexes that get a match.
import numpy as np
var = np.array([4,2,3,4,2,5,2,5,6,7])
# index         0,1,2,3,4,5,6,7,8,9
x=np.where(var == 2)
print(x) #provides u with all index values of 2

y=np.where((var%2) ==0)
print(y)

(array([1, 4, 6], dtype=int64),)
(array([0, 1, 3, 4, 6, 8], dtype=int64),)


In [42]:
# Search Sorted Array : which performs a binary search in the array, and returns the index where the specified value would
# be inserted to maintain the search order.

import numpy as np
var1 = np.array([1,1,2,2,4,4,6,7,8,9,10,11])
# index         0,1,2,3,4,5,617,8,9
x1=np.searchsorted(var1,3) #in var 1 where can i place 5
x2=np.searchsorted(var1,3,side='right')
print(x1)
print(x2)


4
4


In [43]:
import numpy as np
var2 = np.array([1, 2, 2, 2, 4, 4, 6, 7, 8, 9, 10, 11])
# index         0  1  2  3  4  5  6  7  8  9   10  11

x3 = np.searchsorted(var2, 2)               # Find index to insert 2
x4 = np.searchsorted(var2, 2, side="right") # Find index to insert 2 on the right side

print(x3)
print(x4)


1
4


#### Sort Array

In [3]:
import numpy as np
var_1= np.array([4,2,3,1,12,5,22,52,6,7])
print(np.sort(var_1))

var_2=np.array(['v','a','s','t','f'])
print(np.sort(var_2))
print()

var_3= np.array([[4,2,3],[1,12,5],[22,52,6]])
print(np.sort(var_3))

[ 1  2  3  4  5  6  7 12 22 52]
['a' 'f' 's' 't' 'v']

[[ 2  3  4]
 [ 1  5 12]
 [ 6 22 52]]


### Filter

In [6]:
# Filter Array : Getting some elements out of an existing array and
# creating a new array out of them.
# we already have index and slicing tho but when we use filter array we will get 
# a new array created

var_4 = np.array(["a","s","d","f"])
#for elements i want i will mention True and which i don't as False
f=[True,False,False,True]

new_a = var_4[f]

print(new_a)

['a' 'f']


### Shuffle

In [8]:
import numpy as np
var = np.array([1,2,3,4,5])
np.random.shuffle(var) #shuffle function of random

print(var) #on every run values changess

[5 1 3 4 2]


### Unique

In [14]:
import numpy as np
var1 = np.array([1,2,3,4,2,5,6,2,7])
x=np.unique(var1)
y=np.unique(var1,return_index=True)
z=np.unique(var1,return_index=True,return_counts=True)
print(x)
print()
print(y)
print()
print(z)

[1 2 3 4 5 6 7]

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 5, 6, 8], dtype=int64))

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 5, 6, 8], dtype=int64), array([1, 3, 1, 1, 1, 1, 1], dtype=int64))


### Resize

In [21]:
var2 = np.array([1,2,3,4,5,6])

y = np.resize(var2,(2,3)) #2 rows with each 3 elements
print(y)
print()

z = np.resize(var2,(2,8))
print(z)

[[1 2 3]
 [4 5 6]]

[[1 2 3 4 5 6 1 2]
 [3 4 5 6 1 2 3 4]]


### Flatten and Ravel converts 2D array to 1D array

Order : {'C', 'F', 'A','K'}, Optional
    
'C' means to flatten in row-major (C-style) order.

'F' means to flatten in column-major (Fortran-style) order.

'A' means to flatten in column-major order if 'a' is Fortran *contiguous* in memory,row-major order otherwise.

'K' means to flatten 'a' in the order the elements occur in memory

The default is 'C'.

In [35]:
var2 = np.array([1,2,3,4,5,6])

y = np.resize(var2,(3,2)) 

print(y)
print()
#y is a 2D Array

print(y.flatten()) #it gives us normal 1D Array in Row wise
print()
print(y.flatten(order='F')) #Column wise
print()
print("Ravel : ",np.ravel(y))
print()
print("Ravel : ",np.ravel(y,order='F'))
print()
print("Ravel : ",np.ravel(y,order='A'))
print()
print("Ravel : ",np.ravel(y,order='K'))

[[1 2]
 [3 4]
 [5 6]]

[1 2 3 4 5 6]

[1 3 5 2 4 6]

Ravel :  [1 2 3 4 5 6]

Ravel :  [1 3 5 2 4 6]

Ravel :  [1 2 3 4 5 6]

Ravel :  [1 2 3 4 5 6]


### Theory behind this concept

When you have a multi-dimensional array (let's call it 'a') and you want to flatten it into a one-dimensional array, you can specify different orders in which the elements are arranged in the flattened array. The 'A' order specifier is a bit more complex and flexible compared to the 'C' (row-major) and 'F' (column-major) orders.

The 'A' order behaves as follows:

If the array 'a' is stored in memory in a column-major (Fortran-style) contiguous manner, the flattened array will also be in column-major order. In column-major order, the elements from the same column are stored adjacently in memory.

If the array 'a' is not stored in a column-major contiguous manner but is stored in a row-major (C-style) contiguous manner, then the flattened array will be in row-major order. In row-major order, the elements from the same row are stored adjacently in memory.

If the array 'a' is neither column-major contiguous nor row-major contiguous, the flattened array order will depend on the memory layout of 'a'. It will follow the order of elements as they occur in memory.

In simpler terms, 'A' tries to make the flattened array as similar to the original array's memory layout as possible. If the original array is already column-major contiguous, the flattened array will be in column-major order. If the original array is row-major contiguous, the flattened array will be in row-major order. And if the original array has a more complex memory layout, the flattened array will follow the actual order of elements in memory.

This flexibility is particularly useful when dealing with arrays that might have various memory layouts, as 'A' will attempt to maintain the memory locality of the elements in the flattened array as closely as possible to the original array.

If you specifically want to see an example where the 'A' order produces column-major flattening, it's important to note that such cases are rare and might not occur naturally with typical array structures. The 'A' order's behavior is mostly influenced by the memory layout of the array, and in most cases, it would result in row-major order.

### Insert and Delete Functions

In [42]:
#Insert
import numpy as np
var = np.array([1,2,3,4])
print(var)

v=np.insert(var,1,5) #array name , position , value
print(v)

s=np.insert(var,(2,4),5) #inserting multiple data
print(s)

#trying to insert float value
v1=np.insert(var,1,5.8) #array name , position , value
print(v1)


[1 2 3 4]
[1 5 2 3 4]
[1 2 5 3 4 5]
[1 5 2 3 4]


In [50]:
#2D
var1 = np.array([[1,2,3],[1,2,3]])
v1=np.insert(var1,2,6)
print(v1)
print()

v2=np.insert(var1,2,6,axis=0)
print(v2)
print()

v3=np.insert(var1,2,6,axis=1)
print(v3)
print()

v4=np.insert(var1,2,[22,23,24],axis=0)
print(v4)
print()

v5=np.insert(var1,2,[22,23],axis=1)
print(v5)

[1 2 6 3 1 2 3]

[[1 2 3]
 [1 2 3]
 [6 6 6]]

[[1 2 6 3]
 [1 2 6 3]]

[[ 1  2  3]
 [ 1  2  3]
 [22 23 24]]

[[ 1  2 22  3]
 [ 1  2 23  3]]


In [52]:
#We can insert data using append
import numpy as np
var = np.array([1,2,3,4])
print(var)

x=np.append(var,6.5)

print(x)

[1 2 3 4]
[1.  2.  3.  4.  6.5]


In [62]:
#2D
var1 = np.array([[1,2,3],[1,2,3]])
v1=np.append(var1,[[6],[6]],axis=1)
print(v1)

[[1 2 3 6]
 [1 2 3 6]]


In [63]:
#2D
var1 = np.array([[1,2,3],[1,2,3]])
v1=np.append(var1,[[1,2,3]],axis=0)
print(v1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


### Delete

In [66]:
import numpy as np
var1 = np.array([1,2,3,4])
print(var1)
d=np.delete(var1,2) #deleting value at index 2
print(d)

[1 2 3 4]
[1 2 4]


 ### Matrix in NumPy Arrays

In [70]:
#Num of rows x Num of columns

import numpy as np
var=np.matrix([[1,2,3],[1,2,3]])
print(var)
print(type(var))

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>


In [71]:
var1=np.array([[1,2,3],[1,2,3]])
print(var1)
print(type(var1))

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


In [77]:
#Arithmetic Operation in Matrix
var1=np.matrix([[1,2,3],[1,2,3]])
var2=np.matrix([[1,2,3],[1,2,3]])
print(var1+var2)
print()

#in case of multiplication we get error if dimesions dont match
# print(var1*var2)
# ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

# changing data
var1=np.matrix([[1,2],[1,2]])
var2=np.matrix([[1,2],[1,2]])
print(var1*var2) #it is the concept of dot multiplication
print()
print(var1.dot(var2))

[[2 4 6]
 [2 4 6]]

[[3 6]
 [3 6]]

[[3 6]
 [3 6]]


In [90]:
# Matrix Function in Numpy
# Transpose
# Swapaxes
# Inverse
# Determinate
import numpy as np

var1=np.array([[1,2,3],[4,5,6]])
print(var1)
print()

#Transpose
print("Transpose")
print(np.transpose(var1))
print()
print("Other way using .T")
print(var1.T)
print()

#Swapaxes
print("Swapaxes")
print(np.swapaxes(var1,0,1)) #convert 0 axis with 1 axis
print()

print("Doing swapaxes for square matrix")
#Square Matrix
sq=np.matrix([[1,2],[3,4]])
print(sq)
print()
print(np.swapaxes(sq,0,1))
print()

#Inverse Matrix
print("Inverse of a Matrix")
var3=np.matrix([[1,2],[3,4]])
print(var3)
print()
print(np.linalg.inv(var3)) #linalg is nothing but linear algebra
print()



[[1 2 3]
 [4 5 6]]

Transpose
[[1 4]
 [2 5]
 [3 6]]

Other way using .T
[[1 4]
 [2 5]
 [3 6]]

Swapaxes
[[1 4]
 [2 5]
 [3 6]]

Doing swapaxes for square matrix
[[1 2]
 [3 4]]

[[1 3]
 [2 4]]

Inverse of a Matrix
[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]



In [94]:
#Power of a Matrix
print("Power of a Matrix")
#Here we will be using dot function which can be used for smll power
# if power is more we will be using linalg matrix power
# np.linalg.matrix_power(var,n)
# n value can be of 3 types
# zero , <0 , >0

#if n=0 we will be getting Identity matrix
#if n>0 power will be applied
#if n<0 Inverse x Power will be applied

var4 = np.matrix([[1,2],[3,4]])
print(var4)
print()

print(np.linalg.matrix_power(var4,2))
print()

print(np.linalg.matrix_power(var4,0))
print()

print(np.linalg.matrix_power(var4,-2))
print()

Power of a Matrix
[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]



In [98]:
#Determinant of a Matrix
print("Determinant of a Matrix")
var5 = np.matrix([[1,2],[3,4]])
print(var5)
print()

print(np.linalg.det(var5))

Determinant of a Matrix
[[1 2]
 [3 4]]

-2.0000000000000004


### SOME EXTRA STUFFS

In [99]:
#array of a particular value
z=np.full((5,4),5)
print(z)


[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [100]:
 #Create an Identity Matrix
a= np.eye(3) #identiy matrix have same num or rows and columns
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [101]:
#Convert a List to numpy array
list2 = [10,20,30,40,50]

np_array = np.asarray(list2)
print(np_array)

[10 20 30 40 50]
